package settings

type BeltType int

const (
	// Input only
	BELT_TYPE_IN_LEFT      BeltType = iota
	BELT_TYPE_IN_RIGHT     BeltType = iota
	BELT_TYPE_IN_UPLEFT    BeltType = iota
	BELT_TYPE_IN_UPRIGHT   BeltType = iota
	BELT_TYPE_IN_DOWNLEFT  BeltType = iota
	BELT_TYPE_IN_DOWNRIGHT BeltType = iota

	// Output only
	BELT_TYPE_LEFT      BeltType = iota
	BELT_TYPE_RIGHT     BeltType = iota
	BELT_TYPE_UPLEFT    BeltType = iota
	BELT_TYPE_UPRIGHT   BeltType = iota
	BELT_TYPE_DOWNLEFT  BeltType = iota
	BELT_TYPE_DOWNRIGHT BeltType = iota

	// Straight through
	BELT_TYPE_LEFT_RIGHT       BeltType = iota
	BELT_TYPE_RIGHT_LEFT       BeltType = iota
	BELT_TYPE_UPLEFT_DOWNRIGHT BeltType = iota
	BELT_TYPE_DOWNLEFT_UPRIGHT BeltType = iota
	BELT_TYPE_UPRIGHT_DOWNLEFT BeltType = iota
	BELT_TYPE_DOWNRIGHT_UPLEFT BeltType = iota

	// Bend
	BELT_TYPE_LEFT_DOWNRIGHT    BeltType = iota
	BELT_TYPE_LEFT_UPRIGHT      BeltType = iota
	BELT_TYPE_RIGHT_DOWNLEFT    BeltType = iota
	BELT_TYPE_RIGHT_UPLEFT      BeltType = iota
	BELT_TYPE_DOWNRIGHT_LEFT    BeltType = iota
	BELT_TYPE_UPRIGHT_LEFT      BeltType = iota
	BELT_TYPE_DOWNLEFT_RIGHT    BeltType = iota
	BELT_TYPE_UPLEFT_RIGHT      BeltType = iota
	BELT_TYPE_UPLEFT_DOWNLEFT   BeltType = iota
	BELT_TYPE_DOWNLEFT_UPLEFT   BeltType = iota
	BELT_TYPE_UPRIGHT_DOWNRIGHT BeltType = iota
	BELT_TYPE_DOWNRIGHT_UPRIGHT BeltType = iota

	// Straight join
	BELT_TYPE_UPLEFT_DOWNRIGHT_LEFT  BeltType = iota
	BELT_TYPE_DOWNLEFT_UPRIGHT_LEFT  BeltType = iota
	BELT_TYPE_UPRIGHT_DOWNLEFT_RIGHT BeltType = iota
	BELT_TYPE_DOWNRIGHT_UPLEFT_RIGHT BeltType = iota

	BELT_TYPE_UPLEFT_DOWNRIGHT_UPRIGHT   BeltType = iota
	BELT_TYPE_UPRIGHT_DOWNLEFT_UPLEFT    BeltType = iota
	BELT_TYPE_DOWNLEFT_UPRIGHT_DOWNRIGHT BeltType = iota
	BELT_TYPE_DOWNRIGHT_UPLEFT_DOWNLEFT  BeltType = iota

	BELT_TYPE_LEFT_RIGHT_UPLEFT    BeltType = iota
	BELT_TYPE_LEFT_RIGHT_DOWNLEFT  BeltType = iota
	BELT_TYPE_RIGHT_LEFT_UPRIGHT   BeltType = iota
	BELT_TYPE_RIGHT_LEFT_DOWNRIGHT BeltType = iota

	// Two join into one
	BELT_TYPE_UPLEFT_DOWNLEFT_RIGHT  BeltType = iota
	BELT_TYPE_DOWNRIGHT_UPRIGHT_LEFT BeltType = iota

	BELT_TYPE_UPRIGHT_LEFT_DOWNRIGHT BeltType = iota
	BELT_TYPE_RIGHT_UPLEFT_DOWNLEFT  BeltType = iota
	BELT_TYPE_LEFT_DOWNRIGHT_UPRIGHT BeltType = iota
	BELT_TYPE_DOWNLEFT_RIGHT_UPLEFT  BeltType = iota

	// Three join into one
	BELT_TYPE_ALL_RIGHT BeltType = iota
	BELT_TYPE_ALL_LEFT  BeltType = iota

	BELT_TYPE_ALL_DOWNRIGHT BeltType = iota
	BELT_TYPE_ALL_DOWNLEFT  BeltType = iota
	BELT_TYPE_ALL_UPRIGHT   BeltType = iota
	BELT_TYPE_ALL_UPLEFT    BeltType = iota

	// Splitters
	BELT_TYPE_SPLITTER_UPLEFTRIGHT_DOWNLEFTRIGHT BeltType = iota
	BELT_TYPE_SPLITTER_DOWNLEFTRIGHT_UPLEFTRIGHT BeltType = iota

	BELT_TYPE_SPLITTER_LEFTUPLEFT_RIGHTDOWNRIGHT BeltType = iota
	BELT_TYPE_SPLITTER_LEFTDOWNLEFT_RIGHTUPRIGHT BeltType = iota
	BELT_TYPE_SPLITTER_RIGHTUPRIGHT_LEFTDOWNLEFT BeltType = iota
	BELT_TYPE_SPLITTER_RIGHTDOWNRIGHT_LEFTUPLEFT BeltType = iota

	BELT_TYPE_COUNT = iota
)

const (
	// Undergrounds
	BELT_ON_UNDER_IN_LEFT      BeltType = iota
	BELT_ON_UNDER_IN_RIGHT     BeltType = iota
	BELT_ON_UNDER_IN_UPLEFT    BeltType = iota
	BELT_ON_UNDER_IN_UPRIGHT   BeltType = iota
	BELT_ON_UNDER_IN_DOWNLEFT  BeltType = iota
	BELT_ON_UNDER_IN_DOWNRIGHT BeltType = iota

	BELT_ON_UNDER_OUT_LEFT      BeltType = iota
	BELT_ON_UNDER_OUT_RIGHT     BeltType = iota
	BELT_ON_UNDER_OUT_UPLEFT    BeltType = iota
	BELT_ON_UNDER_OUT_UPRIGHT   BeltType = iota
	BELT_ON_UNDER_OUT_DOWNLEFT  BeltType = iota
	BELT_ON_UNDER_OUT_DOWNRIGHT BeltType = iota

	// Splitters
	BELT_ON_SPLITTER_UPLEFTRIGHT_DOWNLEFTRIGHT BeltType = iota
	BELT_ON_SPLITTER_DOWNLEFTRIGHT_UPLEFTRIGHT BeltType = iota

	BELT_ON_SPLITTER_LEFTUPLEFT_RIGHTDOWNRIGHT BeltType = iota
	BELT_ON_SPLITTER_LEFTDOWNLEFT_RIGHTUPRIGHT BeltType = iota
	BELT_ON_SPLITTER_RIGHTUPRIGHT_LEFTDOWNLEFT BeltType = iota
	BELT_ON_SPLITTER_RIGHTDOWNRIGHT_LEFTUPLEFT BeltType = iota

	BELT_ON_COUNT = iota
)

const (
	BELT_TEXTURE_OFFSET_X float32 = 0
	BELT_TEXTURE_OFFSET_Y float32 = 0
)
